table TableImage
	lineageTag: 836473c4-efbe-4079-8e26-ad086b216c63

	measure IconMeasure = ```
			
			SWITCH(
			    TRUE(),
			    [Sales Amount by Due Date] > 1000000, "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAACXBIWXMAABvLAAAb",
			    [Sales Amount by Due Date] <1000000, "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAACXBIWXMAAA7DAAAO",
			    BLANK()
			)
			
			```
		lineageTag: 455c0ec0-05fe-4bdc-82f9-a21b3b285923
		dataCategory: ImageUrl

	column Country
		dataType: string
		lineageTag: f31925cd-180c-4ddd-a287-74f6da7d6c4d
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		lineageTag: 6cdab4e5-1071-4547-8ad2-157383435b8e
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

	partition TableImage = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fctBCoAgEADAr8SepQd0i/pBeHI9LLiFYWvoSt/PPtB1YJwDK1E5DJuScgUDCMuEaCuXikjh5AtxzY+kTKHLHpNyGW85EMAbB3OrWihF6vd/NhFO3wTvXw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Country = _t, Image = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Country", type text}, {"Image", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

